dist: trusty
sudo: required

language: minimal

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.19.0

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo rm -rf /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin/
  - sudo apt-get -q update
  - sudo apt-get install -qy make apt-transport-https ca-certificates curl software-properties-common jq

before_script:
  - uname -a
  - type -a docker-compose && docker-compose version
  - docker version
  - echo "$SSHENC" | base64 -d | gpg -d --passphrase $SSHPWD --batch > /tmp/id_rsa_matchID
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa_matchID
  - ssh-add /tmp/id_rsa_matchID
  - echo "Host * !""$BASTION_HOST" > ~/.ssh/config
  - echo "   ProxyCommand ssh -o StrictHostKeyChecking=no $BASTION_USER@$BASTION_HOST nc %h %p" >> ~/.ssh/config
  - cat ~/.ssh/config


script:
  - git fetch && git describe --tags
  - make docker-check CLOUD_CLI=swift || make docker-build CLOUD_CLI=swift &&
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      make docker-push GIT_BRANCH="$TRAVIS_BRANCH" CLOUD_CLI=swift;
    fi
  - make docker-check CLOUD_CLI=aws || make docker-build CLOUD_CLI=aws &&
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      make docker-push GIT_BRANCH="$TRAVIS_BRANCH" CLOUD_CLI=aws;
      make remote-config-test GIT_BRANCH="$TRAVIS_BRANCH" remote_http_proxy=$REMOTE_HTTP_PROXY remote_https_proxy=$REMOTE_HTTP_PROXY;
    fi

