version: '3.4'

services:
  artillery:
    image: ${APP}-artillery
    build:
      context: ${PERF}
      dockerfile: Dockerfile
    environment:
      - PERF_MAX_USERS=${PERF_MAX_USERS}
      - PERF_WARMUP=${PERF_WARMUP}
      - PERF_SUSTAINED=${PERF_SUSTAINED}
    container_name: ${APP}-artillery
    volumes:
      - ${PERF_SCENARIO}:/artillery/scenario.yml
      - ${PERF_REPORTS}:/artillery/reports/

networks:
  default:
    external:
      name: ${DC_NETWORK}
